# Generated by Django 6.0.2 on 2026-03-19 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(db_index=True, max_length=200)),
                ('ingrediente_activo', models.CharField(db_index=True, max_length=200)),
                ('presentacion', models.CharField(help_text='Ej. Botella 1L, Saco 20kg, Bidón 5L', max_length=100)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'unique_together': {('nombre_comercial', 'presentacion')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Recepción)'), ('SALIDA', 'Salida (Despacho/Venta)'), ('AJUSTE', 'Ajuste (Merma o Corrección)')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_movimiento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(help_text='Operador que escaneó/registró el movimiento', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
